
spring:
  messages:
    basename: i18n/exception
    encoding: utf-8
  jwt:
    secret:kctvjwt
  data:
    cassandra:
      contact-points: 192.168.0.94
      port: 9042
      keyspace-name: kctv
      local-datacenter: datacenter1
      username: biskit
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ktct1020
server:
  port: 8081
logging:
  level:
    sql: trace





