spring:
  profiles: local
  data:
    cassandra:
      contact-points: 192.168.0.76
      port: 9042
      keyspace-name: kctv_dev
      local-datacenter: DC1
      username: biskit
costom:
  host:
    path: http://localhost:8081/v1/verify/
  path:
    images : 'C:\data\'
  wakeuf:
    bryan:
      path: http://192.168.0.91:8099





