spring:
  profiles: jeju
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 4KB
      max-file-size: 200MB
      max-request-size: 215MB
  messages:
    basename: i18n/exception
    encoding: utf-8
  jwt:
    secret: kctvjwt!@#
  mail:
    host: smtp.gmail.com
    port: 587
    username: wakeufjeju@gmail.com
    password: Wuf1234!
    default-encoding: UTF-8
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  data:
    cassandra:

      contact-points:
      - 192.168.161.170
      - 192.168.161.172
      port: 9042
      keyspace-name: kctv
      local-datacenter: jeju-dc
server:
  port: 8101
logging:
  level:
    sql: info
application:
  appVersion: v1
costom:
  host:
    path: http://112.133.52.70:8101/v1/verify/
  path:
    images : ./data/nginx/




