spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 4KB
      max-file-size: 200MB
      max-request-size: 215MB
  profiles:
    active: local
  messages:
    basename: i18n/exception
    encoding: utf-8
  jwt:
    secret: kctvjwt!@#
  data:
    cassandra:
      contact-points: 192.168.0.76
      port: 9042
      keyspace-name: kctv_dev
      local-datacenter: DC1
      username: biskit
  mail:
    host: smtp.gmail.com
    port: 587
    username: wakeufjeju@gmail.com
    password: Wuf1234!
    default-encoding: UTF-8
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
server:
  port: 8081
logging:
  level:
    sql: info
application:
  appVersion: v1



